name: React CI
on: push
jobs:
  run-tests:
    runs-on: ubuntu-latest # virtual environment
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # checkout action or inbuilt action

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install      # install dependencies and defined in package.json

      - name: Run tests
        run: npm test         # run tests defined in package.json